version: '3.8'

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: "bd-wordpress.c5eeqqqgswja.us-east-1.rds.amazonaws.com"
      WORDPRESS_DB_USER: "laura"
      WORDPRESS_DB_PASSWORD: "Helena0250!"
      WORDPRESS_DB_NAME: "bd-wordpress"  # Removi o erro de digitação ("bd-word:press")
      TZ: "America/Sao_Paulo"
    volumes:
      - /mnt/efs:/var/www/html
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: "bd-wordpress.c5eeqqqgswja.us-east-1.rds.amazonaws.com"
      PMA_USER: "laura"
      PMA_PASSWORD: "Helena0250!"
      TZ: "America/Sao_Paulo"
    ports:
      - "8081:80"
    volumes:
      - /mnt/efs:/var/www/html
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

volumes:
  db_data: {}

